import type { StoryGraph } from "../types.js";
import { validateGraph } from "../validators.js";

export function toMarkdown(
	graph: StoryGraph,
	options: { includeMetadata?: boolean; includeAnalysis?: boolean } = {},
): string {
	const v = validateGraph(graph);
	const segments: string[] = [`# ${graph.meta.title}\n\n`];

	if (options.includeMetadata !== false) {
		segments.push("## Story Information\n\n");
		if (graph.meta.genre) segments.push(`- **Genre:** ${graph.meta.genre}\n`);
		segments.push(`- **Version:** ${graph.meta.version}\n`);
		segments.push(`- **Updated:** ${graph.meta.updatedAt}\n\n`);
	}

	if (options.includeAnalysis !== false) {
		segments.push("## Story Analysis\n\n");
		segments.push("### Statistics\n\n");
		segments.push(`- **Events:** ${v.analysis.eventCount}\n`);
		segments.push(`- **Characters:** ${v.analysis.characterCount}\n`);
		segments.push(`- **Conflicts:** ${v.analysis.conflictCount}\n`);
		segments.push(`- **Midpoint:** ${v.analysis.hasMidpoint ? "Yes" : "No"}\n`);
		segments.push(`- **Climax:** ${v.analysis.hasClimax ? "Yes" : "No"}\n`);
		segments.push(`- **Pacing:** ${v.analysis.pacing}\n\n`);

		if (v.issues.length > 0) {
			segments.push("### Issues\n\n");
			for (const i of v.issues) {
				segments.push(`- [${i.severity}] ${i.message}\n`);
			}
			segments.push("\n");
		}
	}

	segments.push("## Characters\n\n");
	for (const c of graph.characters) {
		segments.push(`### ${c.name}\n\n- **Role:** ${c.role}\n`);
		if (c.traits.length > 0)
			segments.push(`- **Traits:** ${c.traits.join(", ")}\n`);
		if (c.motivations.length > 0)
			segments.push(`- **Motivations:** ${c.motivations.join(", ")}\n`);
		segments.push("\n");
	}

	segments.push("## Conflicts\n\n");
	for (const c of graph.conflicts) {
		segments.push(`### ${c.description}\n\n- **Type:** ${c.type}\n`);
		if (c.resolution) segments.push(`- **Resolution:** ${c.resolution}\n`);
		segments.push("\n");
	}

	segments.push("## Events\n\n");

	// Efficiently group events by act in a single pass
	const eventsByAct: Record<number, typeof graph.events> = {
		1: [],
		2: [],
		3: [],
	};
	for (const e of graph.events) {
		if (eventsByAct[e.act]) {
			eventsByAct[e.act].push(e);
		}
	}

	for (const act of [1, 2, 3] as const) {
		const actEvents = eventsByAct[act];
		segments.push(`### Act ${act}\n\n`);
		for (const e of actEvents) {
			segments.push(`#### ${e.label}`);
			if (e.importance !== "rising")
				segments.push(` **[${e.importance.toUpperCase()}]**`);
			segments.push(`\n\n${e.description}\n\n`);
		}
	}

	if (graph.tags.length > 0) {
		segments.push(
			`\n## Tags\n\n${graph.tags.map((t) => `#${t}`).join(" ")}\n\n`,
		);
	}
	segments.push("\n---\n*Generated by bl1nk-visual-mcp v3.0.0*\n");

	const md = segments.join("");

	// Wrap in artifact format
	return `\`\`\`artifact
id: vsp3_complete_setup_guide
name: ${graph.meta.title.replace(/\s+/g, "_")}_Setup_Guide
type: code.markdown
content: |-
${md.replace(/^/gm, "  ")}
\`\`\``;
}
