import type { StoryGraph } from "../types.js";
import { validateGraph } from "../validators.js";

export function toMarkdown(
	graph: StoryGraph,
	options: { includeMetadata?: boolean; includeAnalysis?: boolean } = {},
): string {
	const v = validateGraph(graph);
	let md = `# ${graph.meta.title}\n\n`;

	if (options.includeMetadata !== false) {
		md += "## Story Information\n\n";
		if (graph.meta.genre) md += `- **Genre:** ${graph.meta.genre}\n`;
		md += `- **Version:** ${graph.meta.version}\n`;
		md += `- **Updated:** ${graph.meta.updatedAt}\n\n`;
	}

	if (options.includeAnalysis !== false) {
		md += "## Story Analysis\n\n";
		md += "### Statistics\n\n";
		md += `- **Events:** ${v.analysis.eventCount}\n`;
		md += `- **Characters:** ${v.analysis.characterCount}\n`;
		md += `- **Conflicts:** ${v.analysis.conflictCount}\n`;
		md += `- **Midpoint:** ${v.analysis.hasMidpoint ? "Yes" : "No"}\n`;
		md += `- **Climax:** ${v.analysis.hasClimax ? "Yes" : "No"}\n`;
		md += `- **Pacing:** ${v.analysis.pacing}\n\n`;

		if (v.issues.length > 0) {
			md += "### Issues\n\n";
			for (const i of v.issues) {
				md += `- [${i.severity}] ${i.message}\n`;
			}
			md += "\n";
		}
	}

	md += "## Characters\n\n";
	for (const c of graph.characters) {
		md += `### ${c.name}\n\n- **Role:** ${c.role}\n`;
		if (c.traits.length > 0) md += `- **Traits:** ${c.traits.join(", ")}\n`;
		if (c.motivations.length > 0)
			md += `- **Motivations:** ${c.motivations.join(", ")}\n`;
		md += "\n";
	}

	md += "## Conflicts\n\n";
	for (const c of graph.conflicts) {
		md += `### ${c.description}\n\n- **Type:** ${c.type}\n`;
		if (c.resolution) md += `- **Resolution:** ${c.resolution}\n`;
		md += "\n";
	}

	md += "## Events\n\n";
	for (const act of [1, 2, 3] as const) {
		const actEvents = graph.events.filter((e) => e.act === act);
		md += `### Act ${act}\n\n`;
		for (const e of actEvents) {
			md += `#### ${e.label}`;
			if (e.importance !== "rising")
				md += ` **[${e.importance.toUpperCase()}]**`;
			md += `\n\n${e.description}\n\n`;
		}
	}

	if (graph.tags.length > 0)
		md += `\n## Tags\n\n${graph.tags.map((t) => `#${t}`).join(" ")}\n\n`;
	md += "\n---\n*Generated by bl1nk-visual-mcp v3.0.0*\n";

	// Wrap in artifact format
	return `\`\`\`artifact
id: vsp3_complete_setup_guide
name: ${graph.meta.title.replace(/\s+/g, "_")}_Setup_Guide
type: code.markdown
content: |-
${md.replace(/^/gm, "  ")}
\`\`\``;
}
