import { z } from "zod";
import type { EventNode, StoryGraph } from "../types.js";

// Zod schema for basic validation before generating mermaid
const EventNodeSchema = z.object({
	id: z.string().min(1),
	label: z.string().min(1),
	act: z.number().int().min(1).max(3),
	importance: z.enum([
		"inciting",
		"midpoint",
		"climax",
		"resolution",
		"rising",
	]),
	sequenceInAct: z.number().int().min(1),
});

const StoryGraphSchema = z.object({
	meta: z.object({
		title: z.string().min(1),
		createdAt: z.string(),
		updatedAt: z.string(),
		version: z.string(),
		genre: z.string().optional(),
	}),
	characters: z.array(z.any()), // Basic validation for now
	conflicts: z.array(z.any()),
	events: z.array(EventNodeSchema).min(1, "Story must have at least one event"),
	relationships: z.array(z.any()),
	tags: z.array(z.string()),
});

export function toMermaid(
	graph: StoryGraph,
	options: {
		includeMetadata?: boolean;
		style?: "default" | "dark" | "minimal";
		skipValidation?: boolean;
	} = {},
): string {
	// Validate input data before processing (can be skipped for performance)
	if (options.skipValidation !== true) {
		const validationResult = StoryGraphSchema.safeParse(graph);
		if (!validationResult.success) {
			throw new Error(
				`Invalid story graph data for mermaid generation: ${validationResult.error.errors
					.map((e) => `${e.path.join(".")}: ${e.message}`)
					.join(", ")}`,
			);
		}
	}

	let out = "%% Mermaid diagram generated by bl1nk-visual-mcp\n";
	if (options.includeMetadata !== false)
		out += `%% Title: ${graph.meta.title}\n`;

	const theme =
		options.style === "dark"
			? "dark"
			: options.style === "minimal"
				? "neutral"
				: "default";
	out += `%%{init: {'theme': '${theme}'}}%%\n`;

	out += "graph TD\n";

	// Optimized: Sort events once and use a single pass to group into subgraphs and build connections
	const sortedEvents = [...graph.events].sort((a, b) => {
		if (a.act !== b.act) return a.act - b.act;
		return a.sequenceInAct - b.sequenceInAct;
	});

	let currentAct = -1;
	for (const e of sortedEvents) {
		// Detect act change to open/close subgraphs
		if (e.act !== currentAct) {
			if (currentAct !== -1) out += "  end\n";
			currentAct = e.act;
			out += `  subgraph Act_${currentAct} ["Act ${currentAct}"]\n`;
		}

		const label = e.label.replace(/"/g, "'");
		// Different shapes for different importance
		let shape = `["${label}"]`;
		if (e.importance === "climax") shape = `(("${label}"))`;
		if (e.importance === "midpoint") shape = `> "${label}" ]`;
		if (e.importance === "inciting") shape = `{{ "${label}" }}`;

		out += `    ${e.id}${shape}:::${e.importance}\n`;
	}

	if (currentAct !== -1) out += "  end\n";

	// Build connections between sequential events
	for (let i = 0; i < sortedEvents.length - 1; i++) {
		out += `  ${sortedEvents[i].id} --> ${sortedEvents[i + 1].id}\n`;
	}

	// 4. Character interactions (optional, can be messy in flowchart)
	// graph.relationships.forEach(r => out += `  ${r.from} -.-> ${r.to}\n`);

	// 5. Styling
	out += "\n  classDef inciting fill:#f9f,stroke:#333,stroke-width:2px\n";
	out += "  classDef midpoint fill:#ff9,stroke:#333,stroke-width:2px\n";
	out += "  classDef climax fill:#f96,stroke:#333,stroke-width:4px\n";
	out += "  classDef resolution fill:#9f9,stroke:#333,stroke-width:2px\n";
	out += "  classDef rising fill:#fff,stroke:#333,stroke-width:1px\n";

	return out;
}
