import { z } from "zod";
import type { EventNode, StoryGraph } from "../types.js";

// Zod schema for basic validation before generating mermaid
const EventNodeSchema = z.object({
	id: z.string().min(1),
	label: z.string().min(1),
	act: z.number().int().min(1).max(3),
	importance: z.enum([
		"inciting",
		"midpoint",
		"climax",
		"resolution",
		"rising",
	]),
	sequenceInAct: z.number().int().min(1),
});

const StoryGraphSchema = z.object({
	meta: z.object({
		title: z.string().min(1),
		createdAt: z.string(),
		updatedAt: z.string(),
		version: z.string(),
		genre: z.string().optional(),
	}),
	characters: z.array(z.any()), // Basic validation for now
	conflicts: z.array(z.any()),
	events: z.array(EventNodeSchema).min(1, "Story must have at least one event"),
	relationships: z.array(z.any()),
	tags: z.array(z.string()),
});

export function toMermaid(
	graph: StoryGraph,
	options: {
		includeMetadata?: boolean;
		style?: "default" | "dark" | "minimal";
	} = {},
): string {
	// Validate input data before processing
	const validationResult = StoryGraphSchema.safeParse(graph);
	if (!validationResult.success) {
		throw new Error(
			`Invalid story graph data for mermaid generation: ${validationResult.error.errors
				.map((e) => `${e.path.join(".")}: ${e.message}`)
				.join(", ")}`,
		);
	}

	const segments: string[] = [
		"%% Mermaid diagram generated by bl1nk-visual-mcp\n",
	];
	if (options.includeMetadata !== false) {
		segments.push(`%% Title: ${graph.meta.title}\n`);
	}

	const theme =
		options.style === "dark"
			? "dark"
			: options.style === "minimal"
				? "neutral"
				: "default";
	segments.push(`%%{init: {'theme': '${theme}'}}%%\n`);

	segments.push("graph TD\n");

	// 1. Sort events once and group by Act
	const sortedEvents = [...graph.events].sort((a, b) => {
		if (a.act !== b.act) return a.act - b.act;
		return a.sequenceInAct - b.sequenceInAct;
	});

	const acts: Record<number, EventNode[]> = { 1: [], 2: [], 3: [] };
	for (const e of sortedEvents) {
		if (acts[e.act]) {
			acts[e.act].push(e);
		}
	}

	// 2. Render Subgraphs for Acts using pre-sorted act events
	for (const act of [1, 2, 3] as const) {
		const actEvents = acts[act];
		if (actEvents.length === 0) continue;

		segments.push(`  subgraph Act_${act} ["Act ${act}"]\n`);

		for (const e of actEvents) {
			const label = e.label.replace(/"/g, "'");
			// Different shapes for different importance
			let shape = `["${label}"]`;
			if (e.importance === "climax") shape = `(("${label}"))`;
			if (e.importance === "midpoint") shape = `> "${label}" ]`;
			if (e.importance === "inciting") shape = `{{ "${label}" }}`;

			segments.push(`    ${e.id}${shape}:::${e.importance}\n`);
		}
		segments.push("  end\n");
	}

	// 3. Connect events in sequence using the already sorted array
	for (let i = 0; i < sortedEvents.length - 1; i++) {
		segments.push(`  ${sortedEvents[i].id} --> ${sortedEvents[i + 1].id}\n`);
	}

	// 4. Styling
	segments.push(
		"\n  classDef inciting fill:#f9f,stroke:#333,stroke-width:2px\n",
	);
	segments.push("  classDef midpoint fill:#ff9,stroke:#333,stroke-width:2px\n");
	segments.push("  classDef climax fill:#f96,stroke:#333,stroke-width:4px\n");
	segments.push(
		"  classDef resolution fill:#9f9,stroke:#333,stroke-width:2px\n",
	);
	segments.push("  classDef rising fill:#fff,stroke:#333,stroke-width:1px\n");

	return segments.join("");
}
